language: python
env:
  global:
    - DJANGO_DEBUG=True
    - DJANGO_SECRET_KEY='1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN'
    - DJANGO_ALLOWED_HOSTS=''
    - DJANGO_SETTINGS_MODULE=gtballot.settings.travis
    - DJANGO_STATIC_ROOT=''
  matrix:
    - DJANGO_VERSION=1.4.20
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.1
python:
    - 3.4
    - 3.3
    - 3.2
    - 2.7
    - 2.6
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements/development.txt
  ###- pip install coveralls
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test
  ###- coverage run --source=gtballot manage.py test
##after_success: coveralls
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 2.6
      env: DJANGO_VERSION=1.7.8
    - python: 3.2
      env: DJANGO_VERSION=1.4.20
    - python: 3.3
      env: DJANGO_VERSION=1.4.20
    - python: 3.3
      env: DJANGO_VERSION=1.5.12
    - python: 3.4
      env: DJANGO_VERSION=1.4.20
    - python: 3.4
      env: DJANGO_VERSION=1.5.12
    - python: 3.4
      env: DJANGO_VERSION=1.6.11
  ##allow_failures:
